version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: atez-ecommerce-db
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: secure_password_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce-network

  app:
    build: .
    container_name: atez-ecommerce-app
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ecommerce_db
      DB_USER: ecommerce_user
      DB_PASSWORD: secure_password_2024
      JWT_SECRET: atez_software_jwt_secret_key_2024
      PORT: 3001
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    networks:
      - ecommerce-network
    command: npm run dev

  nginx:
    image: nginx:alpine
    container_name: atez-ecommerce-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - ecommerce-network

volumes:
  postgres_data:

networks:
  ecommerce-network:
    driver: bridge 